### ISSUE TITLE
Not compilable on macOS due to the dependency on RPi.GPIO

### ISSUE THREAD

**Issue by leonidlezner** [rm-hull/luma.emulator#18]
Hello! I'm trying to compile the Python module on my Mac, but it's failing due to the dependency to RPi.GPIO. The RPi.GPIO is as I understand not compilable on OSX.

If it's true, is the dependency really necessary for the emulation? Your screenshots seem to be taken on a Mac, so I don't know if I need a Linux VM or am I just screwing something up :)

**Comment by rm-hull** [comment]
Yes, you're correct: RPi.GPIO wont build on OSX.

The dependency isnt strictly necessary for the emulator; there is probably something we can do to detect where it is being installed (in luma.core), and conditionally install it if not on OSX.

I did run the demos/screenshots on OSX, but probably mangled `$PYTHONPATH` to fudge it to work.

**Comment by thijstriemstra** [comment]
@leonidlezner can you paste some errors (log)?

**Comment by rm-hull** [comment]
@leonidlezner - could you try reinstalling on OSX with:

    $ sudo pip install --upgrade luma.emulator

Let me know how that goes? 
If you get errors, please paste the logs into the comments field.
Which version of OSX are you using?

**Comment by leonidlezner** [comment]
It's working now! Thank you!
