### ISSUE TITLE
1.0.0 release?

### ISSUE THREAD

**Issue by thijstriemstra** [rm-hull/luma.emulator#26]
Because of https://github.com/rm-hull/luma.emulator/commit/51954365a04c36d37fce44d69a82afe80340ac9e and other fixes: https://github.com/rm-hull/luma.emulator/compare/0.2.5...master

**Comment by thijstriemstra** [comment]
@rm-hull with 1.0.0 version nr?

**Comment by thijstriemstra** [comment]
If you agree, make sure to declare it stable here as well: https://github.com/rm-hull/luma.emulator/blob/master/setup.py#L66

**Comment by rm-hull** [comment]
Good point ... would've missed that 😁

**Comment by rm-hull** [comment]
v1.0.0 released: https://pypi.python.org/pypi/luma.emulator
