### ISSUE TITLE
workaround pygame bug #331 causing high load

### ISSUE THREAD

**Issue by commonism** [rm-hull/luma.emulator#30]
First of all - thanks for luma.*
It's great, high quality software with very good documentation, fun to work with.

That said, the issue I'm reporting is not a luma issue.
Certain pygame installations cause high load (100%) even when doing nothing.
There is a bug filed for pygame already (https://github.com/pygame/pygame/issues/331) and even though there is no consent if using "pygame.display.init()" instead of "pygame.init()" helps, it works for me.

Therefore I propose to use pygame.display.init() instead of pygame.init() when initializing pygame (https://github.com/rm-hull/luma.emulator/blob/master/luma/emulator/device.py#L183). 
It helps and and does not harm as luma.emulator does not use audio anyway.

**Comment by thijstriemstra** [comment]
@commonism can you make a pull request so we can run some unit tests against it on travis etc?

**Comment by rm-hull** [comment]
v1.0.1 released to pypi with this fix in it - thanks for pointing out the workaround @commonism 👍
