### ISSUE TITLE
Readthedocs not building

### ISSUE THREAD

**Issue by thijstriemstra** [rm-hull/luma.emulator#52]
Merry xmas!

For some reason the luma.emulator docs aren't being updated on readthedocs. The last build was 2 years ago: https://readthedocs.org/projects/luma-emulator/builds/ You can see the unmaintained badge in https://luma-emulator.readthedocs.io/en/latest/ for example..

**Comment by thijstriemstra** [comment]
maybe you can add me to readthedocs as well, so I can take a look @rm-hull, my username is thijstriemstra

**Comment by rm-hull** [comment]
Hope you had a good Christmas 🎄, and wishing you a good new year. 
I have added you as a maintainer on readthedocs.

**Comment by thijstriemstra** [comment]
thanks, you too!! The rtd build should be fixed now.

**Comment by thijstriemstra** [comment]
ps. can you publish a new release (it drops py3.5) at some point?

**Comment by rm-hull** [comment]
1.4.0 released just so
