### ISSUE TITLE
Pypi token missing?

### ISSUE THREAD

**Issue by thijstriemstra** [rm-hull/luma.emulator#61]
When I tag a new version, e.g. 1.5.0, it starts publishing using github actions but fails with:

```
Notice: Attempting to perform trusted publishing exchange to retrieve a temporary short-lived API token for authentication against https://test.pypi.org/legacy/ due to __token__ username with no supplied password field
Error: Trusted publishing exchange failure: 
```

See https://github.com/rm-hull/luma.emulator/actions/runs/5753077008/job/15595490117#step:7:20

It seems the pypi/repo permission settings for luma.emulator are correct, and should be similar to e.g. luma.oled where it does work. Looks like some token is missing @rm-hull.

**Comment by rm-hull** [comment]
Will check

**Comment by thijstriemstra** [comment]
@rm-hull is it the token that's missing?

**Comment by rm-hull** [comment]
It was a PYPI token missing, but also needed to add https://github.com/rm-hull/luma.emulator/commit/596d373cb2921f48664011de388838c5b23b1749
