### ISSUE TITLE
Provide list of scaling transform types

### ISSUE THREAD

**Issue by thijstriemstra** [rm-hull/luma.emulator#8]
Currently the scaling transform types are hard-coded in the example, e.g. `["none", "identity", "scale2x", "smoothscale", "led_matrix", "seven_segment"]`. This list should be made available in this package instead.

**Comment by rm-hull** [comment]
This could be derived from: `dir(luma.emulator.render.transformer)`

**Comment by rm-hull** [comment]
Accomplished using `__all__` in commit 6f24a4a1db58f9ad4404eb9cc02e67e3fcf64a26 for emulation devices and `[fn for fn in dir(luma.emulator.render.transformer) if fn[0:2] != "__"]` for transformer methods

**Comment by thijstriemstra** [comment]
I'd prefer to have that code in core or here in emulator.
